name: Full Test Automation (Fast)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  # ================= API =================
  api-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install deps
      run: pip install -r test_framework/requirements.txt

    - name: Run API tests
      run: pytest test_framework/tests/api

  # ================= WEB =================
  web-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install deps
      run: |
        pip install -r test_framework/requirements.txt
        pip install playwright
        python -m playwright install --with-deps

    - name: Run Web tests
      run: pytest test_framework/tests/web

  # ================= MOBILE =================
  mobile-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install deps
      run: pip install -r test_framework/requirements.txt

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - uses: android-actions/setup-android@v3

    - name: Create & Start Emulator
      run: |
        sdkmanager "system-images;android-30;google_apis;x86_64"
        echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force

        nohup emulator -avd test -no-window -no-audio -no-boot-anim &
        adb wait-for-device
        until adb shell getprop sys.boot_completed | grep "1"; do sleep 5; done

    - uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Appium
      run: |
        npm install -g appium
        appium driver install uiautomator2

    - name: Start Appium
      run: |
        nohup appium &
        sleep 15

    - name: Run Mobile tests
      run: pytest test_framework/tests/mobile
